version: '3'
services:
  server1:
    image: demo-server
    volumes:
      - "${PWD}/network1.json:/go/src/app/network.json:ro"
    ports:
      - "8080:8080"
      - "4561:4561"
    environment:
      - DELAY=0
  server2:
    image: demo-server
    volumes:
      - "${PWD}/network2.json:/go/src/app/network.json:ro"
    ports:
      - "8081:8080"
      - "4562:4561"
    environment:
      - DELAY=20
  server3:
    image: demo-server
    volumes:
      - "${PWD}/network3.json:/go/src/app/network.json:ro"
    ports:
      - "8082:8080"
      - "4563:4561"
    environment:
      - DELAY=40
  server4:
    image: demo-server
    volumes:
      - "${PWD}/network4.json:/go/src/app/network.json:ro"
    ports:
      - "8083:8080"
      - "4564:4561"
    environment:
      - DELAY=70
  server5:
    image: demo-server
    volumes:
      - "${PWD}/network5.json:/go/src/app/network.json:ro"
    ports:
      - "8084:8080"
      - "4565:4561"
    environment:
      - DELAY=100
